eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
server:
  port: 7300
spring:
  application:
    name: ysc-gateway
zuul:
  prefix: /api #为zuul设置一个公共的前缀
  routes:
    consumer:
      path: /consumer1/**
      serviceId: ysc-consumer
    configConsumer:
      path: /consumer2/**
      serviceId: ysc-consumer